name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    # Convert repository name to lowercase
    - name: Convert repository name to lowercase
      id: lowercaserepo
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "::set-output name=repo::$REPO_NAME"
        echo "Converted repository name: $REPO_NAME"

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ steps.lowercaserepo.outputs.repo }}:latest .

    # Push the Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ steps.lowercaserepo.outputs.repo }}:latest
